package cn.com.atblue.oa.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeDocuments;
import cn.com.atblue.oa.dao.OfficeDocumentsDAO;

public class OfficeDocumentsDAOImpl extends SqlMapClientDaoSupport implements
		OfficeDocumentsDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public OfficeDocumentsDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public void insert(OfficeDocuments record) {
		getSqlMapClientTemplate().insert(
				"OFFICE_DOCUMENTS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public int updateByPrimaryKey(OfficeDocuments record) {
		int rows = getSqlMapClientTemplate().update(
				"OFFICE_DOCUMENTS.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public int updateByPrimaryKeySelective(OfficeDocuments record) {
		int rows = getSqlMapClientTemplate().update(
				"OFFICE_DOCUMENTS.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public OfficeDocuments selectByPrimaryKey(String documentid) {
		OfficeDocuments key = new OfficeDocuments();
		key.setDocumentid(documentid);
		OfficeDocuments record = (OfficeDocuments) getSqlMapClientTemplate()
				.queryForObject(
						"OFFICE_DOCUMENTS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	public int deleteByPrimaryKey(String documentid) {
		OfficeDocuments key = new OfficeDocuments();
		key.setDocumentid(documentid);
		int rows = getSqlMapClientTemplate().delete(
				"OFFICE_DOCUMENTS.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	public List getByFreeSql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_DOCUMENTS.getByFreeSql", map);
	}

	public int getByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_DOCUMENTS.getByFreeSqlCount", sql);
	}

	public List getMapByFreeSql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_DOCUMENTS.getMapByFreeSql", map);
	}

	public int getMapByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_DOCUMENTS.getMapByFreeSqlCount", sql);
	}
}