package cn.com.atblue.oa.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeCirculation;
import cn.com.atblue.oa.dao.OfficeCirculationDAO;

public class OfficeCirculationDAOImpl extends SqlMapClientDaoSupport implements OfficeCirculationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public OfficeCirculationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void insert(OfficeCirculation record) {
        getSqlMapClientTemplate().insert("OFFICE_CIRCULATION.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int updateByPrimaryKey(OfficeCirculation record) {
        int rows = getSqlMapClientTemplate().update("OFFICE_CIRCULATION.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int updateByPrimaryKeySelective(OfficeCirculation record) {
        int rows = getSqlMapClientTemplate().update("OFFICE_CIRCULATION.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public OfficeCirculation selectByPrimaryKey(String cyid) {
        OfficeCirculation key = new OfficeCirculation();
        key.setCyid(cyid);
        OfficeCirculation record = (OfficeCirculation) getSqlMapClientTemplate().queryForObject("OFFICE_CIRCULATION.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int deleteByPrimaryKey(String cyid) {
        OfficeCirculation key = new OfficeCirculation();
        key.setCyid(cyid);
        int rows = getSqlMapClientTemplate().delete("OFFICE_CIRCULATION.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
    
    public List getByFreeSql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_CIRCULATION.getByFreeSql", map);
	}

	public int getByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_CIRCULATION.getByFreeSqlCount", sql);
	}

	public List getMapByFreeSql(String sql) {
		Map map = new HashMap();
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_CIRCULATION.getMapByFreeSql", map);
	}

	public int getMapByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_CIRCULATION.getMapByFreeSqlCount", sql);
	}

	public List getBySql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_CIRCULATION.getBySql", map);
	}

	public int getBySqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_CIRCULATION.getBySqlCount", sql);
	}
}