package cn.com.atblue.oa.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import cn.com.atblue.oa.bean.OfficeDocumentsCheck;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeCirculationCheck;
import cn.com.atblue.oa.dao.OfficeCirculationCheckDAO;

public class OfficeCirculationCheckDAOImpl extends SqlMapClientDaoSupport implements OfficeCirculationCheckDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public OfficeCirculationCheckDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void insert(OfficeCirculationCheck record) {
        getSqlMapClientTemplate().insert("OFFICE_CIRCULATION_CHECK.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int updateByPrimaryKey(OfficeCirculationCheck record) {
        int rows = getSqlMapClientTemplate().update("OFFICE_CIRCULATION_CHECK.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int updateByPrimaryKeySelective(OfficeCirculationCheck record) {
        int rows = getSqlMapClientTemplate().update("OFFICE_CIRCULATION_CHECK.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public OfficeCirculationCheck selectByPrimaryKey(String pkid) {
        OfficeCirculationCheck key = new OfficeCirculationCheck();
        key.setPkid(pkid);
        OfficeCirculationCheck record = (OfficeCirculationCheck) getSqlMapClientTemplate().queryForObject("OFFICE_CIRCULATION_CHECK.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public int deleteByPrimaryKey(String pkid) {
        OfficeCirculationCheck key = new OfficeCirculationCheck();
        key.setPkid(pkid);
        int rows = getSqlMapClientTemplate().delete("OFFICE_CIRCULATION_CHECK.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
    
    public List getByFreeSql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_CIRCULATION_CHECK.getByFreeSql", map);
	}

	public int getByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_CIRCULATION_CHECK.getByFreeSqlCount", sql);
	}

	public List getMapByFreeSql(String sql, PageBean pb) {
		Map map = new HashMap();
		map.put("currentPage", pb.getCurrentPage());
		map.put("pageSize", pb.getPageSize());
		map.put("sql", sql);
		return getSqlMapClientTemplate().queryForList(
				"OFFICE_CIRCULATION_CHECK.getMapByFreeSql", map);
	}

	public int getMapByFreeSqlCount(String sql) {
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"OFFICE_CIRCULATION_CHECK.getMapByFreeSqlCount", sql);
	}

	public OfficeCirculationCheck selectByPrimaryCyid(String cyid) {
        OfficeCirculationCheck key = new OfficeCirculationCheck();
        key.setCyid(cyid);
        OfficeCirculationCheck record = (OfficeCirculationCheck) getSqlMapClientTemplate().queryForObject("OFFICE_CIRCULATION_CHECK.abatorgenerated_selectByPrimaryCyid", key);
        return record;
	}

    public OfficeCirculationCheck selectByPkidCheckMan(String pkid, String checkman){
        Map map = new HashMap();
        map.put("pkid",pkid);
        map.put("checkman", checkman);

        List list = getSqlMapClientTemplate().queryForList("OFFICE_CIRCULATION_CHECK.selectByPkidCheckMan",map);
        if(list!=null && list.size()>0){
            return (OfficeCirculationCheck)list.get(0);
        }
        return null;
    }
}