package cn.com.atblue.oa.dao;

import java.util.List;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeDocuments;

public interface OfficeDocumentsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_DOCUMENTS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    void insert(OfficeDocuments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_DOCUMENTS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    int updateByPrimaryKey(OfficeDocuments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_DOCUMENTS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    int updateByPrimaryKeySelective(OfficeDocuments record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_DOCUMENTS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    OfficeDocuments selectByPrimaryKey(String documentid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_DOCUMENTS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    int deleteByPrimaryKey(String documentid);
    
    List getByFreeSql(String sql, PageBean pb);
    
    int getByFreeSqlCount(String sql);
    
    List getMapByFreeSql(String sql,PageBean pb);
    
    int getMapByFreeSqlCount(String sql);
}