package cn.com.atblue.oa.bean;

import java.util.Date;

public class OfficeDocuments {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String documentid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.QFRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Date qfrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.WJBH
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String wjbh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.MMCD
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String mmcd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.QFR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String qfr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.NGBM
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String ngbm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.BT
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String bt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.HJSX
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String hjsx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.GYFS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Integer gyfs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.ZTC
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String ztc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.LB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String lb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.BZ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String bz;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.ZS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String zs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.CS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String cs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.CB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String cb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.FS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Integer fs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.FWJB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String fwjb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.CJRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Date cjrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.CJR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String cjr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS.STATUS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Integer status;
    private String dxtx;

    public String getDxtx() {
		return dxtx;
	}

	public void setDxtx(String dxtx) {
		this.dxtx = dxtx;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.DOCUMENTID
     *
     * @return the value of OFFICE_DOCUMENTS.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getDocumentid() {
        return documentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.DOCUMENTID
     *
     * @param documentid the value for OFFICE_DOCUMENTS.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setDocumentid(String documentid) {
        this.documentid = documentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.QFRQ
     *
     * @return the value of OFFICE_DOCUMENTS.QFRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Date getQfrq() {
        return qfrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.QFRQ
     *
     * @param qfrq the value for OFFICE_DOCUMENTS.QFRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setQfrq(Date qfrq) {
        this.qfrq = qfrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.WJBH
     *
     * @return the value of OFFICE_DOCUMENTS.WJBH
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getWjbh() {
        return wjbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.WJBH
     *
     * @param wjbh the value for OFFICE_DOCUMENTS.WJBH
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setWjbh(String wjbh) {
        this.wjbh = wjbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.MMCD
     *
     * @return the value of OFFICE_DOCUMENTS.MMCD
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getMmcd() {
        return mmcd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.MMCD
     *
     * @param mmcd the value for OFFICE_DOCUMENTS.MMCD
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setMmcd(String mmcd) {
        this.mmcd = mmcd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.QFR
     *
     * @return the value of OFFICE_DOCUMENTS.QFR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getQfr() {
        return qfr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.QFR
     *
     * @param qfr the value for OFFICE_DOCUMENTS.QFR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setQfr(String qfr) {
        this.qfr = qfr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.NGBM
     *
     * @return the value of OFFICE_DOCUMENTS.NGBM
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getNgbm() {
        return ngbm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.NGBM
     *
     * @param ngbm the value for OFFICE_DOCUMENTS.NGBM
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setNgbm(String ngbm) {
        this.ngbm = ngbm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.BT
     *
     * @return the value of OFFICE_DOCUMENTS.BT
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.BT
     *
     * @param bt the value for OFFICE_DOCUMENTS.BT
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setBt(String bt) {
        this.bt = bt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.HJSX
     *
     * @return the value of OFFICE_DOCUMENTS.HJSX
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getHjsx() {
        return hjsx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.HJSX
     *
     * @param hjsx the value for OFFICE_DOCUMENTS.HJSX
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setHjsx(String hjsx) {
        this.hjsx = hjsx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.GYFS
     *
     * @return the value of OFFICE_DOCUMENTS.GYFS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Integer getGyfs() {
        return gyfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.GYFS
     *
     * @param gyfs the value for OFFICE_DOCUMENTS.GYFS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setGyfs(Integer gyfs) {
        this.gyfs = gyfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.ZTC
     *
     * @return the value of OFFICE_DOCUMENTS.ZTC
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getZtc() {
        return ztc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.ZTC
     *
     * @param ztc the value for OFFICE_DOCUMENTS.ZTC
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setZtc(String ztc) {
        this.ztc = ztc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.LB
     *
     * @return the value of OFFICE_DOCUMENTS.LB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.LB
     *
     * @param lb the value for OFFICE_DOCUMENTS.LB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setLb(String lb) {
        this.lb = lb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.BZ
     *
     * @return the value of OFFICE_DOCUMENTS.BZ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.BZ
     *
     * @param bz the value for OFFICE_DOCUMENTS.BZ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.ZS
     *
     * @return the value of OFFICE_DOCUMENTS.ZS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getZs() {
        return zs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.ZS
     *
     * @param zs the value for OFFICE_DOCUMENTS.ZS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setZs(String zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.CS
     *
     * @return the value of OFFICE_DOCUMENTS.CS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getCs() {
        return cs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.CS
     *
     * @param cs the value for OFFICE_DOCUMENTS.CS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCs(String cs) {
        this.cs = cs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.CB
     *
     * @return the value of OFFICE_DOCUMENTS.CB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getCb() {
        return cb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.CB
     *
     * @param cb the value for OFFICE_DOCUMENTS.CB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCb(String cb) {
        this.cb = cb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.FS
     *
     * @return the value of OFFICE_DOCUMENTS.FS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Integer getFs() {
        return fs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.FS
     *
     * @param fs the value for OFFICE_DOCUMENTS.FS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setFs(Integer fs) {
        this.fs = fs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.FWJB
     *
     * @return the value of OFFICE_DOCUMENTS.FWJB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getFwjb() {
        return fwjb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.FWJB
     *
     * @param fwjb the value for OFFICE_DOCUMENTS.FWJB
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setFwjb(String fwjb) {
        this.fwjb = fwjb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.CJRQ
     *
     * @return the value of OFFICE_DOCUMENTS.CJRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Date getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.CJRQ
     *
     * @param cjrq the value for OFFICE_DOCUMENTS.CJRQ
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCjrq(Date cjrq) {
        this.cjrq = cjrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.CJR
     *
     * @return the value of OFFICE_DOCUMENTS.CJR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.CJR
     *
     * @param cjr the value for OFFICE_DOCUMENTS.CJR
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS.STATUS
     *
     * @return the value of OFFICE_DOCUMENTS.STATUS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS.STATUS
     *
     * @param status the value for OFFICE_DOCUMENTS.STATUS
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}