package cn.com.atblue.oa.bean;

import java.sql.Timestamp;
import java.util.Date;

public class OfficeDocumentsCheck {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.CHEKID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String chekid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String documentid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.CHECKFLAG
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String checkflag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.CHECKTIME
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private Timestamp checktime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.CHECKMAN
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String checkman;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_DOCUMENTS_CHECK.IP
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    private String ip;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.CHEKID
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.CHEKID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getChekid() {
        return chekid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.CHEKID
     *
     * @param chekid the value for OFFICE_DOCUMENTS_CHECK.CHEKID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setChekid(String chekid) {
        this.chekid = chekid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.DOCUMENTID
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getDocumentid() {
        return documentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.DOCUMENTID
     *
     * @param documentid the value for OFFICE_DOCUMENTS_CHECK.DOCUMENTID
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setDocumentid(String documentid) {
        this.documentid = documentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKFLAG
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.CHECKFLAG
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getCheckflag() {
        return checkflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKFLAG
     *
     * @param checkflag the value for OFFICE_DOCUMENTS_CHECK.CHECKFLAG
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCheckflag(String checkflag) {
        this.checkflag = checkflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKTIME
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.CHECKTIME
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public Timestamp getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKTIME
     *
     * @param checktime the value for OFFICE_DOCUMENTS_CHECK.CHECKTIME
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setChecktime(Timestamp checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKMAN
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.CHECKMAN
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getCheckman() {
        return checkman;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.CHECKMAN
     *
     * @param checkman the value for OFFICE_DOCUMENTS_CHECK.CHECKMAN
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setCheckman(String checkman) {
        this.checkman = checkman;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_DOCUMENTS_CHECK.IP
     *
     * @return the value of OFFICE_DOCUMENTS_CHECK.IP
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_DOCUMENTS_CHECK.IP
     *
     * @param ip the value for OFFICE_DOCUMENTS_CHECK.IP
     *
     * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
}