package cn.com.atblue.oa.bean;

import java.sql.Timestamp;
import java.util.Date;

public class OfficeNotice {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String noticeid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.NOTITITLE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String notititle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.NOTIUNIT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String notiunit;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.SUBSCRIBER
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String subscriber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.STARTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private Timestamp startime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.ENDTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private Timestamp endtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.ENDDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private Date enddate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.NOTE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String note;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.RLSDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private Date rlsdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String ip;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.MUSTSIGN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String mustsign;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.ISPUBLIC
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String ispublic;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.STATUS
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE.CONTENT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String content;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.NOTICEID
	 * @return  the value of OFFICE_NOTICE.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getNoticeid() {
		return noticeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.NOTICEID
	 * @param noticeid  the value for OFFICE_NOTICE.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setNoticeid(String noticeid) {
		this.noticeid = noticeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.NOTITITLE
	 * @return  the value of OFFICE_NOTICE.NOTITITLE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getNotititle() {
		return notititle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.NOTITITLE
	 * @param notititle  the value for OFFICE_NOTICE.NOTITITLE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setNotititle(String notititle) {
		this.notititle = notititle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.NOTIUNIT
	 * @return  the value of OFFICE_NOTICE.NOTIUNIT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getNotiunit() {
		return notiunit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.NOTIUNIT
	 * @param notiunit  the value for OFFICE_NOTICE.NOTIUNIT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setNotiunit(String notiunit) {
		this.notiunit = notiunit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.SUBSCRIBER
	 * @return  the value of OFFICE_NOTICE.SUBSCRIBER
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getSubscriber() {
		return subscriber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.SUBSCRIBER
	 * @param subscriber  the value for OFFICE_NOTICE.SUBSCRIBER
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setSubscriber(String subscriber) {
		this.subscriber = subscriber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.STARTIME
	 * @return  the value of OFFICE_NOTICE.STARTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public Timestamp getStartime() {
		return startime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.STARTIME
	 * @param startime  the value for OFFICE_NOTICE.STARTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setStartime(Timestamp startime) {
		this.startime = startime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.ENDTIME
	 * @return  the value of OFFICE_NOTICE.ENDTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public Timestamp getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.ENDTIME
	 * @param endtime  the value for OFFICE_NOTICE.ENDTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setEndtime(Timestamp endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.ENDDATE
	 * @return  the value of OFFICE_NOTICE.ENDDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public Date getEnddate() {
		return enddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.ENDDATE
	 * @param enddate  the value for OFFICE_NOTICE.ENDDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.NOTE
	 * @return  the value of OFFICE_NOTICE.NOTE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.NOTE
	 * @param note  the value for OFFICE_NOTICE.NOTE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.RLSDATE
	 * @return  the value of OFFICE_NOTICE.RLSDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public Date getRlsdate() {
		return rlsdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.RLSDATE
	 * @param rlsdate  the value for OFFICE_NOTICE.RLSDATE
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setRlsdate(Date rlsdate) {
		this.rlsdate = rlsdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.IP
	 * @return  the value of OFFICE_NOTICE.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.IP
	 * @param ip  the value for OFFICE_NOTICE.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.MUSTSIGN
	 * @return  the value of OFFICE_NOTICE.MUSTSIGN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getMustsign() {
		return mustsign;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.MUSTSIGN
	 * @param mustsign  the value for OFFICE_NOTICE.MUSTSIGN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setMustsign(String mustsign) {
		this.mustsign = mustsign;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.ISPUBLIC
	 * @return  the value of OFFICE_NOTICE.ISPUBLIC
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getIspublic() {
		return ispublic;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.ISPUBLIC
	 * @param ispublic  the value for OFFICE_NOTICE.ISPUBLIC
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setIspublic(String ispublic) {
		this.ispublic = ispublic;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.STATUS
	 * @return  the value of OFFICE_NOTICE.STATUS
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.STATUS
	 * @param status  the value for OFFICE_NOTICE.STATUS
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE.CONTENT
	 * @return  the value of OFFICE_NOTICE.CONTENT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE.CONTENT
	 * @param content  the value for OFFICE_NOTICE.CONTENT
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setContent(String content) {
		this.content = content;
	}
}