package cn.com.atblue.oa.bean;

import java.util.Date;

public class OfficeCirculationCheck {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.PKID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String pkid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String cyid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.CHECKMAN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String checkman;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.CHECKFLAG
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String checkflag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.CHECKTIME
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private Date checktime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION_CHECK.SIGN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String sign;
    
    private String taskid;

    public String getTaskid() {
		return taskid;
	}

	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.PKID
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.PKID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.PKID
     *
     * @param pkid the value for OFFICE_CIRCULATION_CHECK.PKID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.CYID
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getCyid() {
        return cyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.CYID
     *
     * @param cyid the value for OFFICE_CIRCULATION_CHECK.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setCyid(String cyid) {
        this.cyid = cyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.CHECKMAN
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.CHECKMAN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getCheckman() {
        return checkman;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.CHECKMAN
     *
     * @param checkman the value for OFFICE_CIRCULATION_CHECK.CHECKMAN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setCheckman(String checkman) {
        this.checkman = checkman;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.CHECKFLAG
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.CHECKFLAG
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getCheckflag() {
        return checkflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.CHECKFLAG
     *
     * @param checkflag the value for OFFICE_CIRCULATION_CHECK.CHECKFLAG
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setCheckflag(String checkflag) {
        this.checkflag = checkflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.CHECKTIME
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.CHECKTIME
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.CHECKTIME
     *
     * @param checktime the value for OFFICE_CIRCULATION_CHECK.CHECKTIME
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION_CHECK.SIGN
     *
     * @return the value of OFFICE_CIRCULATION_CHECK.SIGN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION_CHECK.SIGN
     *
     * @param sign the value for OFFICE_CIRCULATION_CHECK.SIGN
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setSign(String sign) {
        this.sign = sign;
    }
}