package cn.com.atblue.oa.bean;

import java.util.Date;

public class OfficeCirculation {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String cyid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.WJMC
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String wjmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.WJBH
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String wjbh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.LDPS
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String ldps;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.NBYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String nbyj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.CLYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String clyj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.LRSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private Date lrsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.LRR
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String lrr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.LWSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private Date lwsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column OFFICE_CIRCULATION.LWDW
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    private String lwdw;
    
    private String zt;
    private String fs;
    private String swh;
    private String dxtx;
    private String processId;
    private String connectId;
    private String mmcd;
    private String bz;

    public String getZt() {
		return zt;
	}

	public void setZt(String zt) {
		this.zt = zt;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.CYID
     *
     * @return the value of OFFICE_CIRCULATION.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getCyid() {
        return cyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.CYID
     *
     * @param cyid the value for OFFICE_CIRCULATION.CYID
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setCyid(String cyid) {
        this.cyid = cyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.WJMC
     *
     * @return the value of OFFICE_CIRCULATION.WJMC
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getWjmc() {
        return wjmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.WJMC
     *
     * @param wjmc the value for OFFICE_CIRCULATION.WJMC
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setWjmc(String wjmc) {
        this.wjmc = wjmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.WJBH
     *
     * @return the value of OFFICE_CIRCULATION.WJBH
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getWjbh() {
        return wjbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.WJBH
     *
     * @param wjbh the value for OFFICE_CIRCULATION.WJBH
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setWjbh(String wjbh) {
        this.wjbh = wjbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.LDPS
     *
     * @return the value of OFFICE_CIRCULATION.LDPS
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getLdps() {
        return ldps;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.LDPS
     *
     * @param ldps the value for OFFICE_CIRCULATION.LDPS
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setLdps(String ldps) {
        this.ldps = ldps;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.NBYJ
     *
     * @return the value of OFFICE_CIRCULATION.NBYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getNbyj() {
        return nbyj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.NBYJ
     *
     * @param nbyj the value for OFFICE_CIRCULATION.NBYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setNbyj(String nbyj) {
        this.nbyj = nbyj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.CLYJ
     *
     * @return the value of OFFICE_CIRCULATION.CLYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getClyj() {
        return clyj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.CLYJ
     *
     * @param clyj the value for OFFICE_CIRCULATION.CLYJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setClyj(String clyj) {
        this.clyj = clyj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.LRSJ
     *
     * @return the value of OFFICE_CIRCULATION.LRSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.LRSJ
     *
     * @param lrsj the value for OFFICE_CIRCULATION.LRSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.LRR
     *
     * @return the value of OFFICE_CIRCULATION.LRR
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getLrr() {
        return lrr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.LRR
     *
     * @param lrr the value for OFFICE_CIRCULATION.LRR
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setLrr(String lrr) {
        this.lrr = lrr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.LWSJ
     *
     * @return the value of OFFICE_CIRCULATION.LWSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public Date getLwsj() {
        return lwsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.LWSJ
     *
     * @param lwsj the value for OFFICE_CIRCULATION.LWSJ
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setLwsj(Date lwsj) {
        this.lwsj = lwsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column OFFICE_CIRCULATION.LWDW
     *
     * @return the value of OFFICE_CIRCULATION.LWDW
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public String getLwdw() {
        return lwdw;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column OFFICE_CIRCULATION.LWDW
     *
     * @param lwdw the value for OFFICE_CIRCULATION.LWDW
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    public void setLwdw(String lwdw) {
        this.lwdw = lwdw;
    }

	public String getFs() {
		return fs;
	}

	public void setFs(String fs) {
		this.fs = fs;
	}

	public String getSwh() {
		return swh;
	}

	public void setSwh(String swh) {
		this.swh = swh;
	}

	public String getDxtx() {
		return dxtx;
	}

	public void setDxtx(String dxtx) {
		this.dxtx = dxtx;
	}

    public String getProcessId() {
        return processId;
    }

    public void setProcessId(String processId) {
        this.processId = processId;
    }

    public String getConnectId() {
        return connectId;
    }

    public void setConnectId(String connectId) {
        this.connectId = connectId;
    }

    public String getMmcd() {
        return mmcd;
    }

    public void setMmcd(String mmcd) {
        this.mmcd = mmcd;
    }

    public String getBz() {
        return bz;
    }

    public void setBz(String bz) {
        this.bz = bz;
    }
}