package cn.com.atblue.oa.bean;

import java.util.Date;

public class OfficeNoticeCheck {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.CHECKID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String checkid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String noticeid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.CHECKFLAG
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String checkflag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.CHECKTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private Date checktime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.CHECKMAN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String checkman;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.QM
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String qm;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column OFFICE_NOTICE_CHECK.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	private String ip;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.CHECKID
	 * @return  the value of OFFICE_NOTICE_CHECK.CHECKID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getCheckid() {
		return checkid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.CHECKID
	 * @param checkid  the value for OFFICE_NOTICE_CHECK.CHECKID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setCheckid(String checkid) {
		this.checkid = checkid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.NOTICEID
	 * @return  the value of OFFICE_NOTICE_CHECK.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getNoticeid() {
		return noticeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.NOTICEID
	 * @param noticeid  the value for OFFICE_NOTICE_CHECK.NOTICEID
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setNoticeid(String noticeid) {
		this.noticeid = noticeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.CHECKFLAG
	 * @return  the value of OFFICE_NOTICE_CHECK.CHECKFLAG
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getCheckflag() {
		return checkflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.CHECKFLAG
	 * @param checkflag  the value for OFFICE_NOTICE_CHECK.CHECKFLAG
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setCheckflag(String checkflag) {
		this.checkflag = checkflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.CHECKTIME
	 * @return  the value of OFFICE_NOTICE_CHECK.CHECKTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public Date getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.CHECKTIME
	 * @param checktime  the value for OFFICE_NOTICE_CHECK.CHECKTIME
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.CHECKMAN
	 * @return  the value of OFFICE_NOTICE_CHECK.CHECKMAN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getCheckman() {
		return checkman;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.CHECKMAN
	 * @param checkman  the value for OFFICE_NOTICE_CHECK.CHECKMAN
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setCheckman(String checkman) {
		this.checkman = checkman;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.QM
	 * @return  the value of OFFICE_NOTICE_CHECK.QM
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getQm() {
		return qm;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.QM
	 * @param qm  the value for OFFICE_NOTICE_CHECK.QM
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setQm(String qm) {
		this.qm = qm;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column OFFICE_NOTICE_CHECK.IP
	 * @return  the value of OFFICE_NOTICE_CHECK.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column OFFICE_NOTICE_CHECK.IP
	 * @param ip  the value for OFFICE_NOTICE_CHECK.IP
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}
}