package cn.com.atblue.oa.bean;

import java.math.BigDecimal;
import java.util.Date;

public class OfficeFile {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.PKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String pkid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.FKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String fkid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.WJLJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String wjlj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.WJM
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String wjm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.WJLX
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String wjlx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.WJCC
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private BigDecimal wjcc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.LRR
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String lrr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.LRSJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private Date lrsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.LRIP
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private String lrip;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OFFICE_FILE.XZCS
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    private Integer xzcs;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.PKID
     *
     * @return the value of OFFICE_FILE.PKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.PKID
     *
     * @param pkid the value for OFFICE_FILE.PKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.FKID
     *
     * @return the value of OFFICE_FILE.FKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getFkid() {
        return fkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.FKID
     *
     * @param fkid the value for OFFICE_FILE.FKID
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setFkid(String fkid) {
        this.fkid = fkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.WJLJ
     *
     * @return the value of OFFICE_FILE.WJLJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getWjlj() {
        return wjlj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.WJLJ
     *
     * @param wjlj the value for OFFICE_FILE.WJLJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setWjlj(String wjlj) {
        this.wjlj = wjlj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.WJM
     *
     * @return the value of OFFICE_FILE.WJM
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getWjm() {
        return wjm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.WJM
     *
     * @param wjm the value for OFFICE_FILE.WJM
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setWjm(String wjm) {
        this.wjm = wjm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.WJLX
     *
     * @return the value of OFFICE_FILE.WJLX
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getWjlx() {
        return wjlx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.WJLX
     *
     * @param wjlx the value for OFFICE_FILE.WJLX
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setWjlx(String wjlx) {
        this.wjlx = wjlx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.WJCC
     *
     * @return the value of OFFICE_FILE.WJCC
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public BigDecimal getWjcc() {
        return wjcc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.WJCC
     *
     * @param wjcc the value for OFFICE_FILE.WJCC
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setWjcc(BigDecimal wjcc) {
        this.wjcc = wjcc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.LRR
     *
     * @return the value of OFFICE_FILE.LRR
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getLrr() {
        return lrr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.LRR
     *
     * @param lrr the value for OFFICE_FILE.LRR
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setLrr(String lrr) {
        this.lrr = lrr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.LRSJ
     *
     * @return the value of OFFICE_FILE.LRSJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.LRSJ
     *
     * @param lrsj the value for OFFICE_FILE.LRSJ
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.LRIP
     *
     * @return the value of OFFICE_FILE.LRIP
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public String getLrip() {
        return lrip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.LRIP
     *
     * @param lrip the value for OFFICE_FILE.LRIP
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setLrip(String lrip) {
        this.lrip = lrip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OFFICE_FILE.XZCS
     *
     * @return the value of OFFICE_FILE.XZCS
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public Integer getXzcs() {
        return xzcs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OFFICE_FILE.XZCS
     *
     * @param xzcs the value for OFFICE_FILE.XZCS
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    public void setXzcs(Integer xzcs) {
        this.xzcs = xzcs;
    }
}