package cn.com.atblue.oa.dao;

import java.util.List;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeCirculation;

public interface OfficeCirculationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    void insert(OfficeCirculation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int updateByPrimaryKey(OfficeCirculation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int updateByPrimaryKeySelective(OfficeCirculation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    OfficeCirculation selectByPrimaryKey(String cyid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int deleteByPrimaryKey(String cyid);
    
    List getByFreeSql(String sql, PageBean pb);

	int getByFreeSqlCount(String sql);
	
	List getBySql(String sql, PageBean pb);

	int getBySqlCount(String sql);

	List getMapByFreeSql(String sql);

	int getMapByFreeSqlCount(String sql);
	public List getBeanByNbr(String cn, String checkman, PageBean pb);
	public int getBeanByNbrCount(String cn, String checkman);
}