package cn.com.atblue.oa.dao;

import java.util.List;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeDocumentsCheck;

public interface OfficeDocumentsCheckDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS_CHECK
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	void insert(OfficeDocumentsCheck record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS_CHECK
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	int updateByPrimaryKey(OfficeDocumentsCheck record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS_CHECK
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	int updateByPrimaryKeySelective(OfficeDocumentsCheck record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS_CHECK
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	OfficeDocumentsCheck selectByPrimaryKey(String chekid);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table OFFICE_DOCUMENTS_CHECK
	 * 
	 * @abatorgenerated Sun Feb 21 17:24:15 CST 2010
	 */
	int deleteByPrimaryKey(String chekid);

	List getByFreeSql(String sql, PageBean pb);

	int getByFreeSqlCount(String sql);

	List getMapByFreeSql(String sql, PageBean pb);

	int getMapByFreeSqlCount(String sql);
	
	OfficeDocumentsCheck selectByDocumentidCheckMan(String documentid, String checkman);
}