package cn.com.atblue.oa.dao;

import java.util.List;

import cn.com.atblue.common.bean.PageBean;
import cn.com.atblue.oa.bean.OfficeCirculationCheck;
import cn.com.atblue.oa.bean.OfficeDocumentsCheck;

public interface OfficeCirculationCheckDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    void insert(OfficeCirculationCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int updateByPrimaryKey(OfficeCirculationCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int updateByPrimaryKeySelective(OfficeCirculationCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    OfficeCirculationCheck selectByPrimaryKey(String pkid);
    
    OfficeCirculationCheck selectByPrimaryCyid(String cyid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OFFICE_CIRCULATION_CHECK
     *
     * @abatorgenerated Tue Mar 09 09:54:21 CST 2010
     */
    int deleteByPrimaryKey(String pkid);
    
    List getByFreeSql(String sql, PageBean pb);

	int getByFreeSqlCount(String sql);

	List getMapByFreeSql(String sql, PageBean pb);

	int getMapByFreeSqlCount(String sql);

    OfficeCirculationCheck selectByPkidCheckMan(String pkid, String checkman);
}