package cn.com.atblue.oa.dao;

import cn.com.atblue.oa.bean.OfficeNoticeCheck;

import java.util.List;


public interface OfficeNoticeCheckDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	int deleteByPrimaryKey(String checkid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	void insert(OfficeNoticeCheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	void insertSelective(OfficeNoticeCheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	OfficeNoticeCheck selectByPrimaryKey(String checkid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	int updateByPrimaryKeySelective(OfficeNoticeCheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table OFFICE_NOTICE_CHECK
	 * @ibatorgenerated  Wed Dec 23 09:49:51 CST 2009
	 */
	int updateByPrimaryKey(OfficeNoticeCheck record);
	
	void deleteByNoticeid(String noticeid);
	
	String[] getCheckUsersByNoticeid(String noticeid);
	
	List getCheckByNoticeid(String noticeid);
	
	OfficeNoticeCheck getCheckByNoticeidUserid(String userid, String noticeid);
}