package cn.com.atblue.oa.dao;

import cn.com.atblue.oa.bean.OfficeFile;

import java.util.List;

public interface OfficeFileDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    void insert(OfficeFile record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    void insertSelective(OfficeFile record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    OfficeFile selectByPrimaryKey(String pkid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    int updateByPrimaryKeySelective(OfficeFile record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table OFFICE_FILE
     *
     * @ibatorgenerated Wed Dec 23 15:08:35 CST 2009
     */
    int updateByPrimaryKey(OfficeFile record);
    
    List getByFk(String fk);
}